spring:
  profiles:
    include: SECRET
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
#      create : 매번 테이블 새롭게 생성
#      update : 변경 필요한 경우에만 alter, 테이블 없을 경우 create
#      create-drop : 매번 테이블 생성 후 작업 종류 직전 생성 테이블 삭제
#      validate : 테이블에 대한 유효성 검사
#      create로 바꾸지 마라 진짜.
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#      open-in-view: false
    defer-datasource-initialization: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/baggu?serverTimezone=UTC&characterEncoding=utf84&useSSL=false&useUnicode=true
    username: root
    password: A708
  #console color change
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          kakao:
            authorization-grant-type: authorization_code
            client-id: dcea227af64fcf0366810e14b850e4d6
            #테스트용 로컬 리다이렉트
            redirect-uri: http://localhost:3000/kakaoLogin
            # redirect-uri: https://test.baggu.shop/kakaoLogin
#            redirect-uri: http://baggu.shop/kakaoLogin
            # redirect-uri: http://baggu-backend:8080/baggu/auth/callback/kakao
            client-authentication-method: POST
            client-name: kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
#redis설정
  redis:
    host: 127.0.0.1
    port: 6379
  sql:
    init:
      mode:

#log설정
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    region:
      static:
        ap-northeast-2
    stack:
      auto:
        false
server:
  port: 9999

#swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger/api-docs